name: "Checks loop"
on: [push]

jobs:
  check_group_loop:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              function loop(name) {
                  core.startGroup(name);
                  for (var i = 0; i < 10; i++) {
                      core.info("[INFO] " + name + ": " + i );
                 }
                 core.endGroup();
              }

              loop('a');
              loop('b');
