name: "Checks loop"
on: [push]

jobs:
  pr-greeter:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: "Loop"
        run: |
          const core = require('@actions/core')
          function loop(name) {
              core.startGroup(name);
              for (var i = 0; i < 10; i++) {
                  core.info(`[INFO] {${name}}: ${i} { type = log, task = ${name} }`);
             }
             core.endGroup();
          }

          loop('a');
          loop('b');
